name: localstack-action-example
on: push
jobs:
  build:
      runs-on: ubuntu-latest
      services:
        setup-localstack-service:
          image: localstack/localstack
          ports:
            - "4566:4566"
          env:
            SERVICES: "sqs,s3"
            DEFAULT_REGION: us-east-1
            FORCE_NONINTERACTIVE: 1
            AWS_ACCESS_KEY_ID: dummy
            AWS_SECRET_ACCESS_KEY: dummy
          options: >-
            --health-cmd "awslocal s3 mb s3://uploads"
            --health-interval 10s 
            --health-timeout 5s 
            --health-retries 5
      steps:
      - name: Setup AWS-CLI-local
        env:
          # for actuals read from secrets
          LOCALSTACK_API_KEY: 3KxvpMbLld
        run: |
          # Upgrading python to 3.9
          sudo apt install python3.9
          sudo apt install python3-pip
          # Fix for pyOpenSSL error, fixing version for compatibility
          pip install --ignore-installed pyOpenSSL==22.0.0
          # install LocalStack cli and awslocal
          pip3 install localstack awscli-local
          echo "PPB :: awscli installed"
      - name: Run some Tests against LocalStack
        run: |
          echo "Testing S3"
          echo "Create test bucket"
          awslocal s3 mb s3://test-bucket-by-prabhakar
          echo "List buckets"
          awslocal s3 ls
          echo "Test upload"
          touch testFile.txt
          echo "hello world from Prabhakar" >> testFile.txt
          awslocal s3 cp testFile.txt s3://test-bucket-by-prabhakar
          echo "View objects on S3"
          awslocal s3api list-objects --bucket test-bucket-by-prabhakar
          echo "Download and view content of object"
          awslocal s3api get-object --bucket test-bucket-by-prabhakar --key testFile.txt output.txt
          cat output.txt
          echo "delete object in bucket"
          awslocal s3api delete-object --bucket test-bucket-by-prabhakar --key testFile.txt
          echo "delete bucket"
          awslocal s3api delete-bucket --bucket test-bucket-by-prabhakar
          echo "Test Execution complete!" 
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.5
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          # for actuals read from secrets
          aws-access-key-id: dummy
          aws-secret-access-key: dummy
          audience: localhost:4566
      - name: Plan and apply changes
        run: |
          terraform plan -input=false -no-color  
          terraform apply
      - name: Validate terraform apply
        run: |
          echo "Testing Terraform changes"
          echo "List buckets"
          awslocal s3 ls
          echo "Test upload"
          touch testFile.txt
          echo "hello world from Prabhakar" >> testFile.txt
          awslocal s3 cp testFile.txt s3://my-bucket
          echo "View objects on S3"
          awslocal s3api list-objects --bucket my-bucket
          echo "Download and view content of object"
          awslocal s3api get-object --bucket my-bucket --key testFile.txt output.txt
          cat output.txt
