name: localstack-action-example
on: push
jobs:
  example-job:
    #runs-on: ubuntu-latest
    runs-on: macOS-latest
    steps:
      - name: Start LocalStack
        env:
          LOCALSTACK_API_KEY: 3KxvpMbLld
        run: |
          # install LocalStack cli and awslocal
          pip install localstack awscli-local[ver1]
          echo "PPB :: awscli installed"
          # Make sure to pull the latest version of the image
          docker pull localstack/localstack
          echo "PPB :: docker localstack image pull complete"
          # Start LocalStack in the background
          docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack
          echo "PPB :: localstack after start"
          # Wait 30 seconds for the LocalStack container to become ready before timing out
          localstack wait -t 30
          echo "Startup complete"          
      - name: Run some Tests against LocalStack
        run: |
          awslocal s3 mb s3://test-bucket
          awslocal s3 ls
          echo "Test Execution complete!"   
