name: localstack-action-example
on: push
jobs:
  build:
      runs-on: ubuntu-latest
      services:
        aws_local:
          image: localstack/localstack
          ports:
            - "4566:4566"
          env:
            SERVICES: "sqs,s3"
            DEFAULT_REGION: us-east-1
            FORCE_NONINTERACTIVE: 1
            AWS_ACCESS_KEY_ID: dummy
            AWS_SECRET_ACCESS_KEY: dummy
          options: >-
            --health-cmd "awslocal s3 mb s3://uploads"
            --health-interval 10s 
            --health-timeout 5s 
            --health-retries 5
      steps:
      - name: Start LocalStack
        env:
          LOCALSTACK_API_KEY: 3KxvpMbLld
        run: |
          # Upgrading python to 3.9
          sudo apt install python3.9
          sudo apt install python3-pip
          # Upgrade all packages
          # pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U 
          pip install --ignore-installed pyOpenSSL=22.0.0
          # install LocalStack cli and awslocal
          # pip3 install cryptography=36.0.2
          pip3 install localstack awscli-local
          echo "PPB :: awscli installed"
      - name: Run some Tests against LocalStack
        run: |
          awslocal s3 mb s3://test-bucket
          awslocal s3 ls
          echo "Test Execution complete!" 
