name: localstack-action-example
on: push
jobs:
  build:
      runs-on: ubuntu-latest
      services:
        aws_local:
          image: localstack/localstack
          ports:
            - "4566:4566"
          env:
            SERVICES: "sqs,s3"
            DEFAULT_REGION: us-east-1
            FORCE_NONINTERACTIVE: 1
            AWS_ACCESS_KEY_ID: dummy
            AWS_SECRET_ACCESS_KEY: dummy
          options: >-
            --health-cmd "awslocal s3 mb s3://uploads"
            --health-interval 10s 
            --health-timeout 5s 
            --health-retries 5
      steps:
      - name: Run some Tests against LocalStack
        run: |
          awslocal s3 mb s3://test-bucket
          awslocal s3 ls
          echo "Test Execution complete!" 
